"insidebladediameter"=0.01
"height"= 0.015
"bladethickness"= 0.001
"insidebladeradius"= "insidebladediameter" / 2
"D1@Sketch7"="bladethickness"
"D2@Sketch7"="height"
"bladewidth"= "height" * cos ( "bladeangle" )
"bladelength"=0.06
"D1@Boss-Extrude2"="bladelength"
"bladetipradius"= 0.005
"D1@Fillet1"="bladetipradius"
"fusedistance"= 0.0045
"motorrodheight"=0.05
"D1@Boss-Extrude3"="motorrodheight"
"numberofblades"= 3
"D1@CirPattern1"="numberofblades"
"roddiameter"= "bladewidth" * 1.5
"roddepth"= 0.005
"bladeangle"= 45deg
"m"=1
"flatfacedist"= 0.0005
"motorshaftdiameter"=0.002
"D1@Sketch11"="motorshaftdiameter"
"D3@Sketch7"="bladewidth"
"D2@Sketch10"="roddiameter"/2-"fusedistance"
"D1@Sketch10"="roddiameter"
"D2@Sketch11"="flatfacedist"
"bladefilletradius"=0.001
"D1@Fillet4"="bladefilletradius"
